esphome:
  name: bluetoothproxy-m5nanoc6-0e46
  friendly_name: BluetoothProxy-M5nanoC6-0E46

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_0e46

ota:
  - platform: esphome
    password: !secret ota_password_0e46

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BluetoothProxy-M5nanoC6-0E46"
    password: !secret ap_password_0e46

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
    active: true
