---
substitutions:
  name: xiao-ir-mate-7ee554
  friendly_name: XIAO Smart IR Mate

packages:
  Seeed.Xiao IR Proxy: "github://esphome/infrared-proxies/xiao-ir-mate/xiao-ir-mate.yaml"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret api_key_xiao_ir_mate

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
